Make it so

diff --git a/.github/workflows/ci-lint.yml b/.github/workflows/ci-lint.yml
--- a/.github/workflows/ci-lint.yml
+++ b/.github/workflows/ci-lint.yml
@@ -96,9 +96,21 @@ jobs:
       - uses: actions/checkout@v4
         with:
           ref: ${{ inputs.ref }}
-      - name: Check Protobufs
+      - name: Set up mise
+        uses: jdx/mise-action@v2
+      - name: Install mise tools
+        run: mise install
+      - name: Build Protobufs
+        run: make build_proto
+      - name: Check for changes
         run: |
-          make check_proto
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "::error Running 'make build_proto' resulted in changes"
+            echo "::error Please run 'make build_proto' and commit the changes"
+            git status
+            git diff
+            exit 1
+          fi
 
   sdk-lint:
     name: Lint SDKs
