Revert "[ci] enable coverage on merge job" (#14804)
Fixes https://github.com/pulumi/pulumi/issues/14799
Reverts pulumi/pulumi#14727

This PR reverts enabling coverage on the merge job.
prepare-release uses the binaries built during tests which were built
with coverage.

diff --git a/.github/workflows/ci-prepare-release.yml b/.github/workflows/ci-prepare-release.yml
--- a/.github/workflows/ci-prepare-release.yml
+++ b/.github/workflows/ci-prepare-release.yml
@@ -81,6 +81,16 @@ jobs:
           mkdir -p ./artifacts
           mv ./artifacts.tmp/artifacts-*/* ./artifacts
 
+      - name: Ensure coverage not enabled on release
+        working-directory: artifacts
+        run: |
+          if ./pulumi version 2>&1 | grep coverage; then
+            echo 'Aborting! Pulumi binary built with coverage data.'
+            exit 1
+          else
+            echo 'Pulumi binary OK!'
+          fi
+
       - name: Create sums.tmp
         run: mkdir -p ./sums.tmp ./sigs.tmp
 
