upgrade runner images to ubuntu-latest (#19623)
In https://github.com/pulumi/pulumi/pull/18229, we pinned the runner
images to ubuntu 22.04 because we couldn't handle the upgrade. However
eventually we should upgrade to latest again, as 22.04 will be
deprecated eventually, and there shouldn't be a reason why we couldn't
run on latest.

I noticed
https://github.com/pulumi/pulumi/actions/runs/15181755005/job/42692561187?pr=19603
didn't have any available ubuntu runner to pick up my job (though that's
maybe more related to actions being in a degraded state now)

diff --git a/.github/workflows/ci-run-test.yml b/.github/workflows/ci-run-test.yml
--- a/.github/workflows/ci-run-test.yml
+++ b/.github/workflows/ci-run-test.yml
@@ -15,7 +15,7 @@ on:
         description: "Version to produce"
         type: string
       platform:
-        description: "OS to run tests on, e.g.: ubuntu-22.04"
+        description: "OS to run tests on, e.g.: ubuntu-latest"
         required: true
         type: string
 
@@ -374,6 +374,7 @@ jobs:
           GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/application_default_credentials.json
           AWS_ACCESS_KEY: ${{ secrets.AWS_CI_ACCESS_KEY }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CI_ACCESS_SECRET }}
+          DOTNET_VERSION: ${{ fromJson(inputs.version-set).dotnet }}
       - name: Convert Node coverage data
         if: ${{ inputs.platform != 'windows-latest' }}
         run: |
@@ -429,8 +430,10 @@ jobs:
       - name: Summarize Test Times by Individual Test
         continue-on-error: true
         run: |
-          goteststats -statistic test-time test-results/*.json | head -n 100 || \
-                      if [[ $? -eq 141 ]]; then true; else exit $?; fi
+          goteststats -statistic test-time test-results/*.json | head -n 100
+          exit_status=$?
+          # Ignore SIGPIPE (exit status 141)
+          if [[ exit_status -eq 0 || exit_status -eq 141 ]]; then true; else exit $exit_status; fi
       - name: Upload artifacts
         if: ${{ always() }}
         uses: actions/upload-artifact@v4
