remove changelog comment
From our discussion in the ideation meeting yesterday it seemed like
nobody actually finds this comment very useful, and it's just noise on
the PR.  Let's get rid of the comment.  Note that the changelog status
check doesn't actually come from this status check, but separately
from pulumi-bot.  We can safely get rid of this, while keeping that
check.

diff --git a/.github/workflows/on-pr-changelog.yml b/.github/workflows/on-pr-changelog.yml
--- a/.github/workflows/on-pr-changelog.yml
+++ b/.github/workflows/on-pr-changelog.yml
@@ -47,30 +47,15 @@ jobs:
       - uses: actions/setup-go@v5
         with:
           go-version: '>=1.19.0' # decoupled from version sets, only used by changelog tool
-      - name: Changelog
+      - name: Changelog present
         id: changelog
+        if: ${{ inputs.changelog-required }}
         env:
           GITHUB_PR: ${{ inputs.pr-number }}
           PREVIOUS_VERSION: ${{ inputs.base-ref }}
-          CHANGELOG_REQUIRED: ${{ inputs.changelog-required }}
         run: |
-          CHANGELOG="$(./.github/scripts/get-changelog-comment "${PREVIOUS_VERSION}" "${CHANGELOG_REQUIRED}" "${GITHUB_PR}")"
-          ./.github/scripts/set-output CHANGELOG "${CHANGELOG}"
-      - name: Find Comment
-        uses: peter-evans/find-comment@v3
-        id: fc
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          issue-number: ${{ inputs.pr-number }}
-          body-includes: "# Changelog"
-      - name: Create or update comment
-        uses: peter-evans/create-or-update-comment@v4
-        with:
-          token: ${{ secrets.PULUMI_BOT_TOKEN }}
-          comment-id: ${{ steps.fc.outputs.comment-id }}
-          issue-number: ${{ inputs.pr-number }}
-          body: |
-            # Changelog
-
-            ${{ fromJSON(steps.changelog.outputs.CHANGELOG) }}
-          edit-mode: replace
+          CHANGELOG=$(./.github/scripts/get-changelog "${PREVIOUS_VERSION}" --version "[uncommitted]" --filter-open-pr-number "${GITHUB_PR}")
+          if [ -z "${CHANGELOG} ]; then
+            >&2 echo "::error::Changelog not present"
+            exit 1
+          fi
